### ISSUE TITLE
duplicated example.launch

### ISSUE THREAD

**Issue by sktometometo** [jsk-ros-pkg/jsk_control#732]
I am trying to execute samples of this package.

And when I tried to launch example.launch, I had got an error.

```
$ roslaunch jsk_footstep_planner example.launch 
multiple files named [example.launch] in package [jsk_footstep_planner]:
- /home/sktometometo/ros/ws_jsk_ros_pkg/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/launch/example.launch
- /home/sktometometo/ros/ws_jsk_ros_pkg/src/jsk-ros-pkg/jsk_control/jsk_footstep_planner/launch/eusplanner/example.launch
Please specify full path instead
The traceback for the exception was written to the log file

$ diff example.launch eusplanner/example.launch 
$
```

There seems to be two example.launch files in this package and thier name and contens are exactly same.
Is there any special purpose of this file duplication?

**Comment by k-okada** [comment]
@orikuma can you help him?

**Comment by orikuma** [comment]
Historically, jsk_footstep_planner was developed in euslisp, and it was reimplemented in C++ after DRC.
These examples are for the euslisp version, and they seems to be left unintentionally in launch directory.
Therefore, I think they should be only in the eusplanner directory.
However, the euslisp version is no longer maintained as far as I know.
If you just want to see how the C++ version works, you can run `roslaunch jsk_footstep_planner footstep_planner_perception_sample.launch` instead of these examples.

**Comment by k-okada** [comment]
thank you @sktometometo can you update https://github.com/jsk-ros-pkg/jsk_control/blob/master/jsk_footstep_planner/README.md based on @orikuma comment?

**Comment by sktometometo** [comment]
Thank you, @orikuma.
@k-okada , I have created a pullreq about this issue.
Could you please review it?

**Comment by sktometometo** [comment]
I have fixed my error.
